openapi: "3.0.0"
info:
  title: IEMS Employee API
  description: "Swagger definition for IEMS-EMPLOYEE service"
  version: "1.0.0-beta"

servers:
  - url: http://localhost:8080/iems
    description: Local Server for testing the APIs
paths:
  /hrms/employees/{place}:
    get:
      summary: "Operation to Search Employees by Place"
      parameters: 
        - name: place
          in: path
          required: true
          description: Place where employee are based in
          schema:
            type: string
      responses:
        '200': 
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfEmployee'
  /salaries/{searchKey}/{searchValue}:
    get:
      summary: "Operation to find max salary based on location/business unit and supervisor"
      parameters:
        - in: path
          name: searchKey
          required: true
          schema:
            type: string
            enum: ["loc","bu","supervisor"]
            example: "loc"
        - in: path
          name: searchValue
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaxSalaryResponse'
  /salaries/range/{title}:
    get:
      summary: "Operation to find range of salary based on title"
      parameters:
        - in: path
          name: title
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaxSalaryResponse'
  /place/{place}/salary/{increment}:
    get:
      summary: "Operation to provide the increment in salary"
      parameters:
        - in: path
          name: place
          required: true
          schema:
            type: string
        - in: path
          name: increment
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful Update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfEmployee'          
components:
  schemas:
    ArrayOfEmployee:
      type: array
      items:
        $ref: '#/components/schemas/Employee'
    Employee:
      type: object
      properties:
        id: 
          type: integer
        name:
          type: string
        title:
          type: string
        bu:
          type: string
        place:
          type: string
        supervisor:
          type: integer
        competencies:
          type: string
        salary:
          type: number
    MaxSalaryResponse:
      type: object
      properties:
        min: 
          type: number
        max:
          type: number
      
      
    
      
      
            
      